CARLA_CONFIG:
  NUM_OF_VEHICLES: 50
  NUM_OF_WALKERS: 20

AGENT_CONFIG:
  TRANSFORM: {location: [70, 13, 0.5], rotation: [0, 180, 0]}
  BLUEPRINT: vehicle.lincoln.*

SENSOR_CONFIG:
  RGB:
    TRANSFORM: {location: [0, 0, 1.7], rotation: [0, 0, 0]}
    BLUEPRINT: sensor.camera.rgb
    ATTRIBUTE: {image_size_x: 1080, image_size_y: 720, fov: 90}

  DEPTH_RGB:
    TRANSFORM: {location: [0, 0, 1.7], rotation: [0, 0, 0]}
    BLUEPRINT: sensor.camera.rgb
    ATTRIBUTE: {image_size_x: 1080, image_size_y: 720, fov: 90}

  SEG_RGB:
    TRANSFORM: {location: [0, 0, 1.7], rotation: [0, 0, 0]}
    BLUEPRINT: sensor.camera.semantic_segmentation
    ATTRIBUTE: {image_size_x: 1080, image_size_y: 720, fov: 90}

  IMU:
    TRANSFORM: { location: [ 0, 0, 1.7], rotation: [ 0, 0, 0 ] }
    BLUEPRINT: sensor.other.imu

  GNSS:
    TRANSFORM: { location: [ 0, 0, 1.7], rotation: [ 0, 0, 0 ] }
    BLUEPRINT: sensor.other.gnss

  LIDAR:
    TRANSFORM: { location: [ 0, 0, 2.2], rotation: [ 0, 0, 0 ] }
    BLUEPRINT: sensor.lidar.ray_cast
    ATTRIBUTE: {range: 80, rotation_frequency: 20, horizontal_fov: 360.0,  lower_fov: -40, upper_fov: 15, points_per_second: 1280000, channels: 64}

FILTER_CONFIG:
  PRELIMINARY_FILTER_DISTANCE: 80
  MAX_RENDER_DEPTH_IN_METERS: 80
  MIN_VISIBLE_VERTICES_FOR_RENDER: 3
  MAX_OUT_VERTICES_FOR_RENDER: 5

SAVE_CONFIG:
  ROOT_PATH: data/test
  STEP: 5
